# Generated by Django 4.1.3 on 2023-02-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
