# Generated by Django 4.1.3 on 2023-02-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_profile_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
